/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Workspaces_rootRouteImport } from './routes/workspaces/__root'
import { Route as Dashboard_rootRouteImport } from './routes/dashboard/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'

const Workspaces_rootRoute = Workspaces_rootRouteImport.update({
  id: '/workspaces/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_rootRoute = Dashboard_rootRouteImport.update({
  id: '/dashboard/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof Dashboard_rootRoute
  '/workspaces': typeof Workspaces_rootRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/__root': typeof Dashboard_rootRoute
  '/workspaces/__root': typeof Workspaces_rootRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/workspaces' | '/dashboard/' | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/dashboard/__root'
    | '/workspaces/__root'
    | '/dashboard/'
    | '/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Dashboard_rootRoute: typeof Dashboard_rootRoute
  Workspaces_rootRoute: typeof Workspaces_rootRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces/__root': {
      id: '/workspaces/__root'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof Workspaces_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/__root': {
      id: '/dashboard/__root'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof Dashboard_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Dashboard_rootRoute: Dashboard_rootRoute,
  Workspaces_rootRoute: Workspaces_rootRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
